config/routes.rb
Rails.application.routes.draw do
  
  devise_for :admins
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :contents, only: [:index, :show, :top, :about, :detail2, :detail3, :detail4, :detail5, :detail6]
  resources :category2s, only: [:show]
  resources :category3s, only: [:show]
  resources :category4s, only: [:show]
  resources :category5s, only: [:show]
  resources :category6s, only: [:show]
  get 'top' => 'contents#top'
  get 'detail2' => 'contents#detail2'
  get 'detail3' => 'contents#detail3'
  get 'detail4' => 'contents#detail4'
  get 'detail5' => 'contents#detail5'
  get 'detail6' => 'contents#detail6'
  get 'about' => 'contents#about'

  namespace :admin do
    resources :contents, only: [:index, :show, :top, :about, :new, :edit, :create, :update, :destroy]
    resources :main_categories, only: [:create, :destroy]
    resources :category1s, only: [:create, :destroy]
    resources :category2s, only: [:create, :destroy]
    resources :category3s, only: [:create, :destroy]
    resources :category4s, only: [:create, :destroy]
    resources :category5s, only: [:create, :destroy]
    resources :category6s, only: [:create, :destroy]
    get 'top' => 'contents#top'
    get 'about' => 'contents#about'
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category1.rb
class Category1 < ApplicationRecord
    # validates :category1_name, presence: true
    has_many :contents
end

app/models/category10.rb
class Category10 < ApplicationRecord
end

app/models/category2.rb
class Category2 < ApplicationRecord
    # validates :category2_name, presence: true
    has_many :contents
end

app/models/category3.rb
class Category3 < ApplicationRecord
    # validates :category3_name, presence: true
    has_many :contents
end

app/models/category4.rb
class Category4 < ApplicationRecord
    # validates :category4_name, presence: true
    has_many :contents
end

app/models/category5.rb
class Category5 < ApplicationRecord
    # validates :category5_name, presence: true
    has_many :contents
end

app/models/category6.rb
class Category6 < ApplicationRecord
    # validates :category6_name, presence: true
    has_many :contents
end

app/models/category7.rb
class Category7 < ApplicationRecord
end

app/models/category8.rb
class Category8 < ApplicationRecord
end

app/models/category9.rb
class Category9 < ApplicationRecord
end

app/models/content.rb
class Content < ApplicationRecord
    attachment :image

    belongs_to :main_category, optional: true
    belongs_to :category1, optional: true
    belongs_to :category2, optional: true
    belongs_to :category3, optional: true
    belongs_to :category4, optional: true
    belongs_to :category5, optional: true
    belongs_to :category6, optional: true
end

app/models/main_category.rb
class MainCategory < ApplicationRecord
    # validates :main_category_name, presence: true
    has_many :contents
end

app/controllers/admin/contents_controller.rb
class Admin::ContentsController < ApplicationController
    protect_from_forgery :expect => [:create, :destroy]
    before_action :authenticate_admin!

def index
end

def new
    @contents = Content.all
    @content = Content.new
    @main_categories = MainCategory.all.order(id: "DESC")
    @main_category = MainCategory.new
    @category1s = Category1.all.order(id: "DESC")
    @category1 = Category1.new
    @category2s = Category2.all.order(id: "DESC")
    @category2 = Category2.new
    @category3s = Category3.all.order(id: "DESC")
    @category3 = Category3.new
    @category4s = Category4.all.order(id: "DESC")
    @category4 = Category4.new
    @category5s = Category5.all.order(id: "DESC")
    @category5 = Category5.new
    @category6s = Category6.all.order(id: "DESC")
    @category6 = Category6.new
end

def edit
    @content = Content.find(params[:id])
end

def create
    content = Content.new(content_params)
    if content.save
        redirect_to top_path(content)
    else
        redirect_to new_admin_content_path , notice:"コンテンツの追加に失敗しました。"
    end
end
    
def update
    content = Content.find(params[:id])
    content.update(content_params)
    redirect_to top_path
end
    
def destroy
    @content = Content.find(params[:id])
    @content.destroy
    redirect_to top_path
end



private
def content_params
    params.require(:content).permit(:id, :content_name, :content_text, :image, :main_category_id, :category1_id, :category2_id, :category3_id, :category4_id, :category5_id, :category6_id, :create,:destroy)
end

end

app/controllers/category2s_controller.rb
class Category2sController < ApplicationController

def show
    @content = Content.find(params[:id])
    @contents = Content.all
end
    
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController

def top
    @contents = Content.all
end

def about
end

def index
end

def show
    @content = Content.find(params[:id])
    @contents = Content.all
end

end

app/helpers/admin/contents_helper.rb
module Admin::ContentsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/category2s_helper.rb
module Category2sHelper
end

app/helpers/category3s_helper.rb
module Category3sHelper
end

app/helpers/category4s_helper.rb
module Category4sHelper
end

app/helpers/category5s_helper.rb
module Category5sHelper
end

app/helpers/category6s_helper.rb
module Category6sHelper
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/views/admin/contents/edit.html.erb
<h1>コンテンツを編集</h1>
<hr>
<br>
<br>
<div>

<%= form_for([:admin, @content]) do |f| %>

<div>コンテンツ名</div>
<%= f.text_field :content_name %>

<%# <div>コンテンツ説明</div>
<%= f.text_field :content_text %>

<div>コンテンツ画像</div>
<%= f.attachment_field :image %>

<%# <div>メインカテゴリ</div>
<% f.collection_select :main_category_id, MainCategory.all, :id, :main_category_name %>

<div>サブカテゴリ1</div>
<% f.collection_select :category1_id, Category1.all, :id, :category1_name %>

<div>サブカテゴリ2</div>
<% f.collection_select :category2_id, Category2.all, :id, :category2_name %>

<div>サブカテゴリ3</div>
<% f.collection_select :category3_id, Category3.all, :id, :category3_name %>

<div>サブカテゴリ4</div>
<% f.collection_select :category4_id, Category4.all, :id, :category4_name %>

<div>サブカテゴリ5</div>
<% f.collection_select :category5_id, Category5.all, :id, :category5_name %>

<div>サブカテゴリ6</div>
<% f.collection_select :category1_id, Category6.all, :id, :category6_name %>

<% end %>

</div>

app/views/contents/about.html.erb
<div class="title_color">

    <div>
    <%= link_to "TOPに戻る", top_path %>
    </div>

    <h1 class="view_center">ご利用方法</h1>
    <br> 
</div>

<br>

<h2 class="view_center">カテゴリーを選択!</h2>
<div class="image_size">
    <%= image_tag 'ssr1.png' %>
</div>
<br>

<h2 class="view_center">直感で選んでいこう！</h2>
<div class="image_size">
    <%= image_tag 'ssr2.png' %>
    <%= image_tag 'ssr3.png' %>
    <%= image_tag 'ssr4.png' %>
</div>
<%# <img> %>
<br>

<h2 class="view_center">
<p>あなたの求めるものに出会えるかも？</p>
<p>見つかったら決定をclick！</p>
</h2>
<div class="image_size">
    <%= image_tag 'ssr5.png' %>
</div>
<%# <img> %>
<br>

<h2 class="view_center">やってみよう!</h2>
<br>
<h2 class="view_center"><%= link_to "やってみる", top_path %></h2>

app/views/contents/detail2.html.erb
<div>
<%= link_to "戻る", top_path %>
</div>

<h1>あなたの求めるものはコレ</h1>

<div>
<%= attachment_image_tag @content, image, :fill, 170, 170, fallback: "default_content.jpg" , size:'300x300'  %>
</div>

app/views/contents/index.html.erb
<div>
<%= link_to "最初に戻る", top_path %>
</div>

<h1>あなたが求めていたものは、
<%= @content.content_name %>
でした!</h1>

<div>
<%= attachment_image_tag @content, :image, :fill, 170, 170, fallback: "default_content.jpg" , size:'300x300'  %>
</div>

app/views/contents/show.html.erb
<!DOCTYPE html>
<html lang="ja">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>wdyw</title>
    <link rel="stylesheet" href="https://unpkg.com/ress/dist/ress.min.css">
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans+JP:100,500,900&amp;subset=japanese" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
</head>

<body>

<div class="title_color">
    <div>
    <%= link_to "最初に戻る", top_path %>
    </div>

    <h1>あなたが求めていたものは、
    <%= @content.content_name %>
    でした!</h1>
</div>

<hr>

<div class="view_color">
    <br>
    <%# <div class="content_box"> %>
        <div class="image_layout">
        <%= attachment_image_tag @content, :image, :fill, 170, 170, fallback: "default_content.jpg" , size:'300x300'  %>
        </div>
    <br>
    <%# </div> %>


    <%# <% if admin_signed_in? %>
        <%# <div class="text_center"> %>
            <%# <%= link_to "このコンテンツを削除する" , admin_content_path(@content.id) , method: :'delete' %>
        <%# </div> %>
    <%# <% end %>

</div>

</body>
</html>

app/views/contents/top.html.erb
<!DOCTYPE html>
<html lang="ja">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>wdyw</title>
    <link rel="stylesheet" href="https://unpkg.com/ress/dist/ress.min.css">
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans+JP:100,500,900&amp;subset=japanese" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
</head>

<body>


<div class="title_color">

    <%# <% if flash[:notice] %>
        <%# <p class="flash_color"><%= flash[:notice] %>
    <%# <% end %>

    <br>
    <div>
    <%= link_to "ご利用方法", about_path %>
    </div>

    <br>
    <h1 class="view_center">あなたの求めるものを探そう</h1>
    <br>

    <% if admin_signed_in? %>
    <div class="logout_link">
    <%= link_to "ログアウト", destroy_admin_session_path, method: :delete %>
    </div>
    <% end %>

</div>

<hr>

<div class="view_color">
    <br>
    <h2 class="view_center">コンテンツ一覧</h2>
    <%# <div>検索</div> %>
    <br>
    <div class="view_center">
    <% @contents.each do |content| %>
    <%# カテゴリ2がNoContentだった場合非表示 %>
        <% if content.category2.category2_name == 'NoContent' %>
            ・<%= link_to content.content_name, category2_path(content.category1) %>
        <% end %>
    <% end %>
    </div>
    <%# <%= link_to content.category1.category1_name, content_path(content.category1.category1_id)  %>

    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>

    <% if admin_signed_in? %>
        <div>
            <%= link_to "新規コンテンツを追加する", new_admin_content_path %>
        </div>
    <% end %>

<div class="admin_link">
    <%= link_to "管理者入り口", new_admin_session_path %>
</div>

    <br>

</div>
</body>
</html>