config/routes.rb
Rails.application.routes.draw do
  
  devise_for :admins
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :contents, only: [:index, :show, :top, :about, :detail2, :detail3, :detail4, :detail5, :detail6]
  resources :category2s, only: [:show]
  resources :category3s, only: [:show]
  resources :category4s, only: [:show]
  resources :category5s, only: [:show]
  resources :category6s, only: [:show]
  get 'top' => 'contents#top'
  get 'detail2' => 'contents#detail2'
  get 'detail3' => 'contents#detail3'
  get 'detail4' => 'contents#detail4'
  get 'detail5' => 'contents#detail5'
  get 'detail6' => 'contents#detail6'
  get 'about' => 'contents#about'

  namespace :admin do
    resources :contents, only: [:index, :show, :top, :about, :new, :edit, :create, :update, :destroy]
    resources :main_categories, only: [:create, :destroy]
    resources :category1s, only: [:create, :destroy]
    resources :category2s, only: [:create, :destroy]
    resources :category3s, only: [:create, :destroy]
    resources :category4s, only: [:create, :destroy]
    resources :category5s, only: [:create, :destroy]
    resources :category6s, only: [:create, :destroy]
    get 'top' => 'contents#top'
    get 'about' => 'contents#about'
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category1.rb
class Category1 < ApplicationRecord
    # validates :category1_name, presence: true
    has_many :contents
end

app/models/category10.rb
class Category10 < ApplicationRecord
end

app/models/category2.rb
class Category2 < ApplicationRecord
    # validates :category2_name, presence: true
    has_many :contents
end

app/models/category3.rb
class Category3 < ApplicationRecord
    # validates :category3_name, presence: true
    has_many :contents
end

app/models/category4.rb
class Category4 < ApplicationRecord
    # validates :category4_name, presence: true
    has_many :contents
end

app/models/category5.rb
class Category5 < ApplicationRecord
    # validates :category5_name, presence: true
    has_many :contents
end

app/models/category6.rb
class Category6 < ApplicationRecord
    # validates :category6_name, presence: true
    has_many :contents
end

app/models/category7.rb
class Category7 < ApplicationRecord
end

app/models/category8.rb
class Category8 < ApplicationRecord
end

app/models/category9.rb
class Category9 < ApplicationRecord
end

app/models/content.rb
class Content < ApplicationRecord
    attachment :image

    belongs_to :main_category, optional: true
    belongs_to :category1, optional: true
    belongs_to :category2, optional: true
    belongs_to :category3, optional: true
    belongs_to :category4, optional: true
    belongs_to :category5, optional: true
    belongs_to :category6, optional: true
end

app/models/main_category.rb
class MainCategory < ApplicationRecord
    # validates :main_category_name, presence: true
    has_many :contents
end

app/controllers/admin/category4s_controller.rb
class Admin::Category4sController < ApplicationController
    protect_from_forgery :expect => [:create, :destroy]
    # before_action :authenticate_admin!

def create
    @category4 = Category4.new(category4_params)
    @category4.save
end

def destroy
    @category4 = Category4.find(params[:id])
    @category4.destroy
end

private
def category4_params
    params.require(:category4).permit(:category4_name)
end

end

app/controllers/category4s_controller.rb
class Category4sController < ApplicationController

def show
    @contents = Content.all
    @content = Content.find(params[:id])
end

end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController

def top
    @contents = Content.all
end

def about
end

def index
end

def show
    @content = Content.find(params[:id])
    @contents = Content.all
end

end

app/helpers/admin/category4s_helper.rb
module Admin::Category4sHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/category2s_helper.rb
module Category2sHelper
end

app/helpers/category3s_helper.rb
module Category3sHelper
end

app/helpers/category4s_helper.rb
module Category4sHelper
end

app/helpers/category5s_helper.rb
module Category5sHelper
end

app/helpers/category6s_helper.rb
module Category6sHelper
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/views/category4s/show.html.erb
<!DOCTYPE html>
<html lang="ja">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>wdyw</title>
    <link rel="stylesheet" href="https://unpkg.com/ress/dist/ress.min.css">
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans+JP:100,500,900&amp;subset=japanese" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
</head>

<body>



<div class="title_color">
    <div>
    <%= link_to "トップ画面へ戻る", top_path %>
    </div>

    <h1 class="view_center">あなたの求めるものは？</h1>
    <br>
    <%# <div class="view_center">what do you want?</div> %>
</div>

<hr>

<div class="view_color">
    <br>

    <div  class="view_center">気分で選ぼう！</div>

    <%# 手前で押したカテゴリを表示したい %>
    <%# <div  class="category_title">
    <p>select:<%= @content.content_name %>
    <%# </div> %>

    <%# カテゴリ1の情報を持って入ってきてそれに紐付いたカテゴリ2を一覧表示 %>
    <%# カテゴリ2がNoContentなら表示しない %>
    <%# カテゴリ3がNoContentの場合表示する %>
    <br>

    <div class="flexcontainer">
        <% @contents.each do |content| %>
            <% if content.category3_id == @content.id %>
                <% if content.category4.category4_name == 'NoContent' %>
                <% else %>
                    <% if content.category5.category5_name == 'NoContent' %>
                            <div class="flexitem">
                                <div class="content_box">
                                    <p><%= content.content_name %></p>
                                    <%= attachment_image_tag content, :image, :fill, 170, 170, fallback: "default_content.jpg" , size:'170x170' %>
                                <p>
                                    <%= link_to "関連を表示する" , category5_path(content.category4_id) %>
                                    <%= link_to "これに決定!" , content_path(content.id) %>
                                </p>
                                </div>
                            </div>
                    <% else %>
                    <% end %>
                <% end %>
            <% else %>
            <% end %>
        <% end %>
    </div>


    <br>
    <br>

</div>

</body>
</html>